# Generated by Django 4.1.5 on 2023-01-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tel',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='연락처'),
        ),
    ]
